apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: db-stateful-class
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage2
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: db-stateful-class
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/vol2